#!/usr/bin/env bash
#Bash script that display to infinity and beyond indefinitely
#with a sleep 2 in between each iteration
#I am invincible!!! when recieving a SIGTERM signal

i=1
trap 'echo "I am invincible!!!"' SIGTERM
while [ $i ]
do
	echo "To infinity and beyond"
	sleep 2
done
