#!/usr/bin/env bash
#This bash script prints numbers until 20
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
	 4) echo "bad luck from china"
	;;
	 9) echo "bad luck from japan"
	;;
	 17) echo "bad luck from Italy"
	;;
	esac
	x=$(( x + 1 ))
done	
