#!/usr/bin/env bash
#Bash script that displays: the content of the current director#In a list format where only the part of the name after the
#first dash is displayed
for i in *;
do
	echo "$i" | cut -d'-' -f2
done
